# Fetching Data from API using Python

In this notebook, we will fetch movie data from TMDB API, convert JSON data into a Pandas DataFrame, and export the final dataset as a CSV file.

We will learn:

- What an API response looks like
- How to use `requests`
- How to convert JSON into DataFrame
- How to handle pagination
- How to save data as CSV

In [24]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

## API Key Safety

We should never write our API key directly inside the notebook because this notebook will be uploaded to GitHub.

Instead, we will store the API key inside a `.env` file.

In [25]:
load_dotenv()

api_key = os.getenv('TMDB_API_KEY')

if api_key:
    print("API key loaded successfully")
else:
    print("API key not found")

API key loaded successfully

## Fetch Data from TMDB API

We will use the Top Rated Movies endpoint:

`https://api.themoviedb.org/3/movie/top_rated`

This endpoint returns movie data in JSON format.

In [26]:
url = f'https://api.themoviedb.org/3/movie/top_rated?api_key={api_key}&page=1'

response = requests.get(url)
print(response.status_code)

200

In [27]:
data = response.json()

In [28]:
data.keys()

dict_keys(['page', 'results', 'total_pages', 'total_results'])

In [29]:
movies = data['results']
movies[0]

{'adult': False,
 'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
 'genre_ids': [18, 80],
 'id': 278,
 'title': 'The Shawshank Redemption',
 'original_language': 'en',
 'original_title': 'The Shawshank Redemption',
 'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
 'popularity': 52.3376,
 'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
 'release_date': '1994-09-23',
 'softcore': False,
 'video': False,
 'vote_average': 8.7,
 'vote_count': 30265}

In [30]:
df = pd.DataFrame(movies)
df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,52.3376,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.700,30265
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",41.5315,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.686,22852
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,27.3249,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,False,False,8.571,13857
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,Schindler's List,en,Schindler's List,The true story of how businessman Oskar Schind...,26.9609,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,False,False,8.568,17392
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,12 Angry Men,en,12 Angry Men,The defense and the prosecution have rested an...,22.9436,/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg,1957-04-10,False,False,8.560,9940

In [31]:
df = df[
    [
        "id",
        "title",
        "overview",
        "release_date",
        "popularity",
        "vote_average",
        "vote_count"
    ]
]

df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,52.3376,8.700,30265
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.5315,8.686,22852
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.3249,8.571,13857
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,26.9609,8.568,17392
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,22.9436,8.560,9940

## Pagination

The API gives data page by page.

One page contains around 20 movies.  
To collect more movies, we need to loop through multiple pages.

In [32]:
total_pages = data['total_pages']
total_results = data['total_results']

print("Total pages:", total_pages)
print("Total results:", total_results)

Total pages: 542
Total results: 10832

For practice, we are fetching only the first 10 pages instead of all available pages.  
This keeps the notebook fast and avoids unnecessary API calls while learning.

In [33]:
all_movies=[]

for page in range(1,11):
    url = f'https://api.themoviedb.org/3/movie/top_rated?api_key={api_key}&page={page}'
    
    response = requests.get(url)
    data = response.json()
    movies = data['results']
    all_movies.extend(movies)

len(all_movies)

200

In [34]:
movies_df = pd.DataFrame(all_movies)
movies_df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,52.3376,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.700,30265
1,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",41.5315,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.686,22852
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,27.3249,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,False,False,8.571,13857
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,Schindler's List,en,Schindler's List,The true story of how businessman Oskar Schind...,26.9609,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,False,False,8.568,17392
4,False,/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg,[18],389,12 Angry Men,en,12 Angry Men,The defense and the prosecution have rested an...,22.9436,/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg,1957-04-10,False,False,8.560,9940

In [35]:
movies_df = movies_df[
    [
        "id",
        "title",
        "overview",
        "release_date",
        "popularity",
        "vote_average",
        "vote_count"
    ]
]

movies_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,52.3376,8.700,30265
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.5315,8.686,22852
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.3249,8.571,13857
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,26.9609,8.568,17392
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,22.9436,8.560,9940

In [36]:
movies_df.shape

(200, 7)

In [37]:
movies_df.to_csv('TMDB_top_rated_movies.csv', index=False)
print("csv created successfully")

csv created successfully

In [38]:
check_df=pd.read_csv("TMDB_top_rated_movies.csv")
check_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,52.3376,8.700,30265
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,41.5315,8.686,22852
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,27.3249,8.571,13857
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,26.9609,8.568,17392
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,22.9436,8.560,9940

## Final Summary

In this notebook, we learned how to:

- Call an API using Python
- Read JSON response
- Extract useful data
- Convert JSON data into a Pandas DataFrame
- Handle pagination
- Export the final dataset as a CSV file

This is a beginner-friendly data collection project using APIs.